# Generated by Django 4.1.3 on 2024-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), ('|', 'Pipe (|)'), ('\t', 'Tab (   )'), (' ', 'Space ( )'), (';', 'Semicolon (;)')], default=',', max_length=5),
        ),
    ]
