# Generated by Django 4.1.3 on 2024-04-21 21:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_schema_column_separator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schema',
            new_name='Scheme',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='schema',
            new_name='scheme',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='schema',
            new_name='scheme',
        ),
    ]
