# Generated by Django 4.1.3 on 2024-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_schema_scheme_rename_schema_column_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.IntegerField(choices=[(0, 'Full name'), (1, 'Address'), (2, 'Text'), (3, 'Integer')], default=0),
        ),
    ]
